### ISSUE TITLE
Sobre a estrutura do projeto

### ISSUE THREAD

**Issue by ctcruz** [RafaelBarbosatec/flutter_news#9]
Olá amigo, gostei muito da estrutura do app e também li os dois artigos que você publicou sobre o desenvolvimento do APP. Gostaria de saber quais técnicas e padrões de projeto que você utilizou pra desenvolver o mesmo para que eu possa me aprofundar mais no assunto. Se tiver links sobre esses padrões ficarei muito grato. 
Obrigado.

**Comment by RafaelBarbosatec** [comment]
Oi @ctcruz ! tudo bem? Mil desculpas pela demora por responder! Esse final de ano estou meio corrido, nem tive muito tempo de contribuir com a comunidade com mais conteúdo .
Mas qualquer coisa manda um email pra mim para rafaelbarbosatec@gmail.com que podemos conversar ou até mesmo marcar uma call.
Abraços !
